flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-1.2.1.0
- aeson-compat-0.3.7.1
- aeson-pretty-0.8.5
- ansi-terminal-0.7
- appar-0.1.4
- async-2.1.1.1
- attoparsec-0.13.2.0
- attoparsec-iso8601-1.0.0.0
- auto-update-0.1.4
- base-compat-0.9.3
- base-orphans-0.6
- base64-bytestring-1.0.0.1
- bifunctors-5.4.2
- blaze-builder-0.4.0.2
- blaze-html-0.9.0.1
- blaze-markup-0.8.0.0
- byteable-0.1.1
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- bytestring-lexing-0.5.0.2
- call-stack-0.1.0
- case-insensitive-1.2.0.10
- cereal-0.5.4.0
- cipher-aes-0.2.11
- clientsession-0.9.1.2
- cmdargs-0.10.17
- colour-2.3.3
- comonad-5.0.2
- conduit-1.2.11
- conduit-extra-1.1.16
- contravariant-1.4
- cookie-0.4.2.1
- cprng-aes-0.6.1
- crypto-api-0.13.2
- crypto-cipher-types-0.0.9
- crypto-random-0.0.9
- css-text-0.1.2.2
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- deepseq-generics-0.2.0.0
- distributive-0.5.3
- dlist-0.8.0.3
- easy-file-0.2.1
- email-validate-2.3.1
- entropy-0.3.8
- exceptions-0.8.3
- fail-4.9.0.0
- fast-logger-2.4.10
- foundation-0.0.13
- free-4.12.4
- hashable-1.2.6.1
- hedis-0.9.9
- hex-0.1.2
- http-api-data-0.3.7.1
- http-date-0.0.6.1
- http-types-0.9.1
- http2-1.6.3
- integer-logarithms-1.0.2
- iproute-1.7.1
- kan-extensions-5.0.2
- lens-4.15.4
- lifted-base-0.2.3.11
- math-functions-0.2.1.0
- memory-0.14.6
- mmorph-1.1.0
- monad-control-1.0.2.2
- monad-logger-0.3.25
- monad-loops-0.4.3
- mtl-2.2.1
- mwc-random-0.13.6.0
- network-2.6.3.2
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parallel-3.2.1.1
- parsec-3.1.11
- path-pieces-0.2.1
- persistent-2.7.0
- persistent-template-2.5.2
- prelude-extras-0.4.0.3
- primitive-0.6.2.0
- profunctors-5.2.1
- psqueues-0.2.3.0
- random-1.1
- reflection-2.1.2
- resource-pool-0.2.3.2
- resourcet-1.1.9
- safe-0.3.15
- scanner-0.2
- scientific-0.3.5.2
- securemem-0.1.9
- semigroupoids-5.2.1
- semigroups-0.18.3
- setenv-0.1.1.3
- shakespeare-2.0.14
- silently-1.2.5
- simple-sendfile-0.2.25
- skein-1.0.9.4
- stm-2.4.4.1
- stm-chans-3.0.0.4
- streaming-commons-0.1.18
- stringsearch-0.3.6.6
- tagged-0.8.5
- tagsoup-0.14.1
- text-1.2.2.2
- th-abstraction-0.2.5.0
- th-lift-0.7.7
- th-lift-instances-0.1.11
- time-locale-compat-0.1.1.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.3.1
- unix-time-0.3.7
- unordered-containers-0.2.8.0
- uri-bytestring-0.2.3.3
- utf8-string-1.0.1.1
- uuid-types-1.0.3
- vault-0.3.0.7
- vector-0.12.0.1
- vector-th-unbox-0.2.1.6
- void-0.7.2
- wai-3.2.1.1
- wai-extra-3.0.20.0
- wai-logger-2.3.0
- warp-3.2.13
- word8-0.1.3
- xss-sanitize-0.3.5.7
- yaml-0.8.23.3
- yesod-1.4.5
- yesod-core-1.4.36
- yesod-form-1.4.15
- yesod-persistent-1.4.2
- zlib-0.6.1.2
- cabal-doctest-1.0.2
resolver: ghc-8.0.1
